[package]
name = "august-build"
description = """
Task-based build system with a custom syntax and modularity features for all your artifact construction needs.
"""
version = "0.5.0-dev"
edition = "2021"
authors = ["Hayden Brown <scratchcat458@gmail.com>"]
repository = "https://github.com/ScratchCat458/august-build"
homepage = "https://august-build.web.app"
documentation = "https://docs.rs/august-build"
keywords = ["build", "august", "build-system"]
categories = [
  "command-line-utilities",
  "development-tools::build-utils",
  "development-tools",
]
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.4"
chumsky = "0.9"
thiserror = "1"
owo-colors = "4"
dircpy = "0.3"
clap = { version = "4", features = ["derive", "string"] }
clap_complete = "4"
comfy-table = "7"
which = "6"


[[bin]]
name = "august"
path = "src/main.rs"
