# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: August Build
site_url: https://august-build.web.app
site_description: Task-based build system with a custom syntax and modularity features for all your artifact construction needs.
repo_url: https://github.com/ScratchCat458/august-build
repo_name: ScratchCat458/august-build
copyright: Copyright &copy; 2023 Hayden Brown (ScratchCat458) under the MIT license

theme:
  name: material
  logo: images/August Minimal.svg
  favicon: images/August Build.svg
  icon:
    repo: fontawesome/brands/github 
  palette: 
    scheme: slate
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.suggest
    - content.code.copy

plugins:
  - search
  - social

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Welcome:
    - index.md
  - Getting Started:
    - getting-started/index.md
    - getting-started/installation.md
    - getting-started/the-basics.md
    - getting-started/extending-august.md
    - getting-started/command-reference.md
    - getting-started/cli.md
  - Modules:
    - modules/cargo.md
  - Implementation:
    - implementation/index.md
    - Concepts:
      - implementation/concepts/index.md
      - implementation/concepts/structural.md
      - implementation/concepts/pragmas.md
      - implementation/concepts/tasks.md
      - implementation/concepts/commands.md
      - implementation/concepts/command-def.md
      - implementation/concepts/external-modules.md
    - Parsing:
      - implementation/parsing/index.md
      - implementation/parsing/tokenisation.md
      - implementation/parsing/syntax.md
      - implementation/parsing/module-linking.md
