on:
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

name: Rust Standard CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test
        run: cargo test

      - name: Run cargo clippy
        run: cargo clippy
